### ISSUE TITLE
Search and top buttons are overlapping 

### ISSUE THREAD

**Issue by OlegIlyenko** [sphereio/sphere-sunrise-dmexco#120] opened 2015-09-14 12:24 UTC
Tested it in chrome (also tried to force refresh it, but it still there)

![sunrise_-_tops](https://cloud.githubusercontent.com/assets/156569/9849564/5883fa28-5aec-11e5-8338-852e55670b52.png)

**Comment by lauraluiz** [comment] 2015-09-14 16:54
When does it happen? I cannot reproduce it.

**Comment by OlegIlyenko** [comment] 2015-09-14 16:57
it's not easy to reproduce. You can try to navigate to some page and then press F5 (with chrome)

**Comment by lauraluiz** [comment] 2015-09-14 17:33
I cannot reproduce it, but it will be fixed when sign in button is back anyway.

**Closed by lauraluiz** 2015-09-14 17:33 UTC
Labels: bug
